server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/products_shop"
    username: root
    password: nguyenvu
  jpa:
    hibernate:
      naming:
        physical-strategy: com.codenguyenvu.helloworld.helpers.LowerCaseNamingStrategy
jpa:
  hibernate:
    ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

